baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "garybuckle"
theme = "PaperMod"

[params]
  mainSections = ["posts"]
  paginate = 5  # number of posts per page
  # optional PaperMod params
  home = true   # show homepage with posts

  [menu]
    [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 2