baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "garybuckle"
theme = "PaperMod"

[params]
  customCSS = ["css/custom.css"]  # 👈 load your plain CSS here
  DateFormat = "02.01.2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2